site_name: FRAM core
site_author: NVE
site_description: >-
  FRAM documentation site

repo_url: https://github.com/NVE/fram-core
repo_name: NVE/fram-core

theme:
  name: "material"
  icon:
    repo: fontawesome/brands/github
  features:
  - content.footnote.tooltips
  - content.tabs.link
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.instant
  - navigation.instant.prefetch
  - navigation.instant.progress
  - navigation.path
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest

nav:
  - index.md
  - reference.md
  - tech_details.md

markdown_extensions:
- tables
- attr_list

plugins:
  - mkdocstrings:
     handlers:
        python:
          options:  
            show_submodules: true
            show_root_heading: true
            show_root_full_path: true
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_source: true    
  - mike
  - search
  - macros
  - table-reader

extra_css:
  - docs/css/mkdocstrings.css

extra:
  version:
    provider: mike
  framlinks:
    fram: https://nve.github.io/fram/
    fram-why-core: https://nve.github.io/fram/why_core_model/
    fram-HL-components: https://nve.github.io/fram/why_components/
    data: https://nve.github.io/fram-data/
    demo: https://github.com/NVE/fram-demo
    julesAPI: https://nve.github.io/fram-jules/
    nve: https://www.nve.no/english/
